version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"  # Порт для подключения извне

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"    # Внутренний порт Kafka

  db:
    image: 'postgres:16'
    container_name: event-service-db
    environment:
         - 'POSTGRES_DB=${DB_URL:-postgres}'
         - 'POSTGRES_USER=${DB_USER:-postgres}'
         - 'POSTGRES_PASSWORD=${DB_PASSWORD:-root}'
    ports:
         - '5432:5432'
